spring.application.name=Lankatools


# DATABASE


spring.datasource.url=jdbc:mysql://localhost:3306/lankatools?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=xyz#SQL2
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / HIBERNATE

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# THYMELEAF
spring.thymeleaf.cache=false


# FILE UPLOADS
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
upload.dir=uploads/


# MAIL CONFIGURATION (MOCK INTERCEPT ACTIVE)
# ==========================================
spring.mail.host=localhost
spring.mail.port=25
spring.mail.username=lankatools.testmail@gmail.com
spring.mail.password=mock-password


# SERVER
server.port=8080